// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr1tpw_Io_iMGTGTGuV3s1T2PTfmnNH7c',
    appId: '1:513006185811:web:68e17e90219ead946c45a6',
    messagingSenderId: '513006185811',
    projectId: 'storesapp-f22d0',
    authDomain: 'storesapp-f22d0.firebaseapp.com',
    storageBucket: 'storesapp-f22d0.firebasestorage.app',
    measurementId: 'G-6DQVM4TNY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqbOmyQReVoM5CNgZLNuJIhmTF3buWzrM',
    appId: '1:513006185811:android:9a3c8c5808cd54f46c45a6',
    messagingSenderId: '513006185811',
    projectId: 'storesapp-f22d0',
    storageBucket: 'storesapp-f22d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmAk_LZnezEv33k2oQcawNiDdVKoj3JPs',
    appId: '1:513006185811:ios:2fa191185230c77c6c45a6',
    messagingSenderId: '513006185811',
    projectId: 'storesapp-f22d0',
    storageBucket: 'storesapp-f22d0.firebasestorage.app',
    iosBundleId: 'com.ao8r.splashSingInUpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmAk_LZnezEv33k2oQcawNiDdVKoj3JPs',
    appId: '1:513006185811:ios:2fa191185230c77c6c45a6',
    messagingSenderId: '513006185811',
    projectId: 'storesapp-f22d0',
    storageBucket: 'storesapp-f22d0.firebasestorage.app',
    iosBundleId: 'com.ao8r.splashSingInUpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr1tpw_Io_iMGTGTGuV3s1T2PTfmnNH7c',
    appId: '1:513006185811:web:efa3f02c1d9dcfe16c45a6',
    messagingSenderId: '513006185811',
    projectId: 'storesapp-f22d0',
    authDomain: 'storesapp-f22d0.firebaseapp.com',
    storageBucket: 'storesapp-f22d0.firebasestorage.app',
    measurementId: 'G-H4C9LR24EQ',
  );
}
